# Generated by Django 4.2.7 on 2023-11-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skladnik',
            old_name='jarski',
            new_name='vege',
        ),
    ]
